### ISSUE TITLE
unresolved import `palette::ShiftHue`: no `ShiftHue` in the root

### ISSUE THREAD

**Issue by ProgrammingLife** [Ogeon/palette#265]
## How To Reproduce
Tried to run this example: https://github.com/Ogeon/palette/blob/master/palette/examples/hue.rs but it didn't compile in my case. When I do following I get:
```
use palette::{ FromColor, Hsl, IntoColor, Lch, Srgb }; // this line works fine
use palette::{ ShiftHue }; // Here I have: unresolved import `palette::ShiftHue`: no `ShiftHue` in the root
```

What should I do wrong?

## Additional Details

* Cargo.toml entry: ```palette = "0.6"```
* Rust version(s): rustc 1.57.0 (f1edd0429 2021-11-29)
* Target platform: Linux Mint 19.1

**Comment by Ogeon** [comment]
Hi, I have been reworking the traits for the next version, so the examples will not work with the 0.6.0 version for now. That a look at the 0.6.0 tag for examples that uses the 0.6.0 traits: https://github.com/Ogeon/palette/tree/0.6.0/palette/examples

**Comment by Ogeon** [comment]
I'm closing this since it was a version misunderstanding. Feel free to open again if you think it's a different issue.
